name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - gh-pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Debug Info
        run: |
          echo "Current directory: $(pwd)"
          echo "Directory contents:"
          ls -la
          echo "Node version: $(node -v)"
          echo "NPM version: $(npm -v)"

      - name: Install Dependencies
        run: |
          if [ -d "onboarding-project" ]; then
            cd onboarding-project
            npm ci
          else
            echo "Error: onboarding-project directory not found"
            exit 1
          fi

      - name: Build
        run: |
          if [ -d "onboarding-project" ]; then
            cd onboarding-project
            echo "Creating .env file..."
            echo "REACT_APP_OPENAI_API_KEY=${{ secrets.REACT_APP_OPENAI_API_KEY }}" > .env
            echo "Building application..."
            CI=false npm run build
            echo "Build completed"
            echo "Build directory contents:"
            ls -la build/
            rm .env
          else
            echo "Error: onboarding-project directory not found"
            exit 1
          fi

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: onboarding-project/build
          branch: gh-pages
          clean: true
          commit-message: "Deploy to GitHub Pages" 